---
title: "621 Regression Tree Sandbox"
author: "Michael D'Acampora"
date: "May 13, 2018"
output: html_document
---

A basic regression tree was used on this data set to predict default, which partitions the data into smaller groups that are more homogenous with respect to the response. 
```{r}

cc_data <- read.csv("https://raw.githubusercontent.com/621-Group2/Final-Project/master/UCI_Credit_Card.csv", header = TRUE)

train_data <- read.csv("https://raw.githubusercontent.com/621-Group2/Final-Project/master/trainData.csv", header = TRUE)
test_data <- read.csv("https://raw.githubusercontent.com/621-Group2/Final-Project/master/testData.csv", header = TRUE)



head(cc_data)
nrow(cc_data)
head(train_data)
nrow(train_data)
head(test_data)
nrow(test_data)
```

```{r}
library(rpart)
library(rpart.plot)
# grow tree
m1 <- rpart(target ~ .,  data = train_data, method = 'anova')
print(m1)
# additional plots
par(mfrow=c(1,2)) 
rsq.rpart(m1)
```

```{r}
#printcp(m1) # display the results
plotcp(m1) # visualize cross-validation results
summary(m1) # detailed summary of splits
```

```{r}
rpart.plot(m1, type=3, digits=3, fallen.leaves=TRUE)
```


run prediction on the test data, find the mean absolute error from original data set to predictions
```{r}
library(Metrics)
p1 <- predict(m1, test_data)
head(p1)
plot(p1, residuals(m2))

mse(test_data$target, p1)
rmse(test_data$target, p1)
mae(test_data$target, p1)
sse(test_data$target, p1)


```












